services:
  products-service:
    hostname: products-ms
    container_name: products-ms
    image: widew3b/cn1g9-products:latest
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=products-ms
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@cn1g9_tp?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=CN1G9
      - SPRING_DATASOURCE_PASSWORD=cu'b32i-Eu!}d*S
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.driver.OracleDriver
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=4
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_HIBERNATE<=INFO
      - RABBITMQ_HOST=ip-10-0-128-42.ec2.internal
    restart: unless-stopped