services:
  bff-service:
    image: widew3b/bff-cn1g9:amd64
    container_name: bff-cn1g9
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - PRODUCTS_SERVICE_HOST=http://10.0.140.54:8081
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=products-cn1-grupo9
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@cn1g9_tp?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=CN1G9
      - SPRING_DATASOURCE_PASSWORD=cu'b32i-Eu!}d*S
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.driver.OracleDriver
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=4
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_HIBERNATE<=INFO
    volumes:
      - ./wallet:/app/wallet:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"