services:
  products-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=${SERVER_PORT:-8080}
      - SPRING_APPLICATION_NAME=cn1-grupo9
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@cn1g9_high?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-CN1G9}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.driver.OracleDriver
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=4
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_HIBERNATE=INFO
    volumes:
      - ./wallet:/app/wallet:ro
    restart: unless-stopped