services:
  bff-cn1g9:
    build:
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "8080:8080"
    networks:
      - shared
networks:
  shared:
    external: true