services:
  bff-cn1g9:
    build:
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "8080:8080"
    networks:
      - shared
    environment:
      - PRODUCTS_SERVICE_HOST=http://products-ms:8080
      - SALES_SERVICE_HOST=http://sales-ms:8080
      - PROMOTIONS_SERVICE_HOST=http://promotions-ms:8080
      - INVENTORY_SERVICE_HOST=http://inventory-ms:8080
networks:
  shared:
    external: true