services:
  promotions-ms:
    hostname: promotions-ms
    container_name: promotions-ms
    restart: unless-stopped
    build:
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "8083:8080"
    environment:
      - KAFKA_BROKER_1_HOST=ip-10-0-141-134.ec2.internal:9091
      - KAFKA_BROKER_2_HOST=ip-10-0-141-134.ec2.internal:9092
      - KAFKA_BROKER_3_HOST=ip-10-0-141-134.ec2.internal:9093
    networks:
      - shared
  networks:n
shared:
  external: true