services:
  promotions-ms:
    build:
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "8084:8080"
    networks:
      - shared
networks:
  shared:
    external: true