services:
  sales-ms:
    hostname: sales-ms
    container_name: sales-ms
    image: widew3b/cn1g9-sales:latest
    ports:
      - "8082:8080"
    environment:
      - PRODUCTS_SERVICE_HOST=http://10.0.140.54:8081
      - KAFKA_BROKER_1_HOST=ip-10-0-141-134.ec2.internal:9091
      - KAFKA_BROKER_2_HOST=ip-10-0-141-134.ec2.internal:9092
      - KAFKA_BROKER_3_HOST=ip-10-0-141-134.ec2.internal:9093
      - KAFKA_BOOTSTRAP_STRING="ip-10-0-141-134.ec2.internal:9091,ip-10-0-141-134.ec2.internal:9092,ip-10-0-141-134.ec2.internal:9093"
    networks:
      - shared
networks:
  shared:
    external: true