server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never
spring:
  application:
    name: cn1-grupo9
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  datasource:
    url: jdbc:oracle:thin:@cn1g9_high?TNS_ADMIN=./wallet
    username: CN1G9
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 4
      connection-timeout: 30000
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.hibernate: ${LOGGING_LEVEL_ORG_HIBERNATE:INFO}
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE