spring:
  application:
    name: promotions-ms-cn1-grupo9
  kafka:
    bootstrap-servers:
      - kafkabroker1:9091
      - kafkabroker2:9092
      - kafkabroker3:9093
    consumer:
      bootstrap-servers:
        - kafkabroker1:9091
        - kafkabroker2:9092
        - kafkabroker3:9093
      group-id: promotions-ms-consumer-group
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  datasource:
    url: jdbc:oracle:thin:@cn1g9_high?TNS_ADMIN=/app/wallet
    username: CN1G9
    password: cu'b32i-Eu!}d*S
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 4
      connection-timeout: 30000
queues:
  sales: sale_finished
  stock: stock_updated