services:
  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq/mnesia
    restart: unless-stopped
    networks:
      - shared
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-1
    hostname: zookeeper-1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: |
      server.1: zookeeper-1:2888:3888
      server.2: zookeeper-2:2888:3888
      server.3: zookeeper-3:2888:3888
    networks:
      - shared
  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-2
    hostname: zookeeper-2
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: |
        server.1: zookeeper-1:2888:3888
        server.2: zookeeper-2:2888:3888
        server.3: zookeeper-3:2888:3888
    networks:
      - shared
  zookeeper-3:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-3
    hostname: zookeeper-3
    ports:
      - "2183:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: |
        server.1: zookeeper-1:2888:3888
        server.2: zookeeper-2:2888:3888
        server.3: zookeeper-3:2888:3888
    networks:
      - shared
  kafkabroker1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafkabroker1
    hostname: kafkabroker1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "29091:29091"
    networks:
      - shared
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafkabroker1:9091,EXTERNAL://localhost:29091'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9091,EXTERNAL://0.0.0.0:29091'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  kafkabroker2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafkabroker2
    hostname: kafkabroker2
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "29092:29092"
    networks:
      - shared
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafkabroker2:9092,EXTERNAL://localhost:29092'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  kafkabroker3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafkabroker3
    hostname: kafkabroker3
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "29093:29093"
    networks:
      - shared
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafkabroker3:9093,EXTERNAL://localhost:29093'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:29093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  kafbat-ui:
    depends_on:
      - kafkabroker1
      - kafkabroker2
      - kafkabroker3
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "1337:8080"
    networks:
      - shared
    environment:
      KAFKA_CLUSTERS_0_NAME: clustercn1grupo9
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkabroker1:9091,kafkabroker2:9092,kafkabroker3:9093
      DYNAMIC_CONFIG_ENABLED: 'true'
networks:
  shared:
    name: shared
    driver: bridge