services:
  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq/mnesia
    restart: unless-stopped
    networks:
      - shared
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-1
    hostname: zookeeper-1
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper-1:/var/lib/zookeeper/data
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"
      ZOOKEEPER_QUORUM_LISTEN_ON_ALL_IPS: 'true'
      ZOOKEEPER_LOG_LEVEL: WARN
    networks:
      - shared
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5
  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-2
    hostname: zookeeper-2
    depends_on:
      - zookeeper-1
    ports:
      - "2182:2181"
    volumes:
      - ./zookeeper-2:/var/lib/zookeeper/data
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"
      ZOOKEEPER_QUORUM_LISTEN_ON_ALL_IPS: 'true'
      ZOOKEEPER_LOG_LEVEL: WARN
    networks:
      - shared
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5
  zookeeper-3:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-3
    hostname: zookeeper-3
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - "2183:2181"
    volumes:
      - ./zookeeper-3:/var/lib/zookeeper/data
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"
      ZOOKEEPER_QUORUM_LISTEN_ON_ALL_IPS: 'true'
      ZOOKEEPER_LOG_LEVEL: WARN
    networks:
      - shared
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5
  kafkabroker1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafkabroker1
    hostname: kafkabroker1
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
    ports:
      - "29091:29091"
    networks:
      - shared
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafkabroker1:9091,EXTERNAL://localhost:29091'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9091,EXTERNAL://0.0.0.0:29091'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_SEGMENT_BYTES: 134217728
      KAFKA_LOG_CLEANUP_POLICY: 'delete'
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9091" ]
      interval: 10s
      timeout: 5s
      retries: 5
  kafkabroker2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafkabroker2
    hostname: kafkabroker2
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
    ports:
      - "29092:29092"
    networks:
      - shared
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafkabroker2:9092,EXTERNAL://localhost:29092'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_SEGMENT_BYTES: 134217728
      KAFKA_LOG_CLEANUP_POLICY: 'delete'
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
  kafkabroker3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafkabroker3
    hostname: kafkabroker3
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
    ports:
      - "29093:29093"
    networks:
      - shared
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafkabroker3:9093,EXTERNAL://localhost:29093'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:29093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_SEGMENT_BYTES: 134217728
      KAFKA_LOG_CLEANUP_POLICY: 'delete'
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9093" ]
      interval: 10s
      timeout: 5s
      retries: 5
  kafbat-ui:
    depends_on:
      kafkabroker1:
        condition: service_healthy
      kafkabroker2:
        condition: service_healthy
      kafkabroker3:
        condition: service_healthy
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "1337:8080"
    networks:
      - shared
    environment:
      KAFKA_CLUSTERS_0_NAME: clustercn1grupo9
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkabroker1:9091,kafkabroker2:9092,kafkabroker3:9093
      DYNAMIC_CONFIG_ENABLED: 'true'
networks:
  shared:
    name: shared
    driver: bridge