services:
  inventory-ms:
    hostname: inventory-ms
    container_name: inventory-ms
    restart: unless-stopped
    image: widew3b/cn1g9-inventory:latest
    ports:
      - "8084:8080"
    environment:
      - PRODUCTS_SERVICE_HOST=http://ip-10-0-136-236.ec2.internal:8081
      - KAFKA_BROKER_1_HOST=ip-10-0-128-42.ec2.internal:9091
      - KAFKA_BROKER_2_HOST=ip-10-0-128-42.ec2.internal:9092
      - KAFKA_BROKER_3_HOST=ip-10-0-128-42.ec2.internal:9093