spring.datasource.url=jdbc:postgresql://tokyo-prod-1.postgres.database.azure.com:5432/forum_schema?currentSchema=public
spring.datasource.username=forum_user
spring.datasource.password=forum_schema123

# === JPA / Hibernate ===
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Setting to validate since we're using Flyway for migrations
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# === Flyway Migration ===
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# === Logging ===
logging.level.org.springframework=INFO
logging.level.dev.bast.foro=DEBUG
logging.level.org.flywaydb=DEBUG

# === JWT Configuration ===
app.jwtSecret=bezKoderSecretKeyJwtTokenKeySecureRandomSecuritySignatureAlgorithmHS512PaddingIsBestWhenLonger
app.jwtExpirationMs=86400000

# === SpringDoc OpenAPI / Swagger ===
springdoc.api-docs.path=/api/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=true
springdoc.paths-to-match=/api/**
