spring:
  application:
    name: inventory-ms-cn1-grupo9
  kafka:
    bootstrap-servers:
      - kafkabroker1:9091
      - kafkabroker2:9092
      - kafkabroker3:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers:
        - kafkabroker1:9091
        - kafkabroker2:9092
        - kafkabroker3:9093
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers:
        - kafkabroker1:9091
        - kafkabroker2:9092
        - kafkabroker3:9093
      group-id: inventory-ms-consumer-group
      properties:
        spring.json.trusted.packages: com.grupo9.inventorymscn1grupo9.sales
        spring.json.value.default.type: com.grupo9.inventorymscn1grupo9.sales.SaleEvent
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  datasource:
    url: jdbc:oracle:thin:@cn1g9_high?TNS_ADMIN=/app/wallet
    username: CN1G9
    password: cu'b32i-Eu!}d*S
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 4
      connection-timeout: 30000
queues-kafka:
  stock-topic: stock_updated
  sale-finished-topic: sale_finished
server:
  port: 8080